### ISSUE TITLE
The request to the rpc server often throws a timeout exception.

### ISSUE THREAD

**Issue by xiangpengm** [matter-labs/zksync-v2-issues#1]
**Describe the issue**
The request to the rpc server often throws a timeout exception.

**Expected behavior**
Beforee zksync testnet version almost raise exception

**Minimal Reproducible Example Code**
curl --location --request POST 'https://zksync2-testnet.zksync.dev/' \
--header 'Content-Type: application/json' \
--data-raw '{"method":"eth_call","params":[{"to":"0xfcfb989b985d4af15d2e4e70d2de1710326f0164","data":"0xf5a75c1d00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000005000000000000000000000000260b6cf38e59fee9d0903389124b65a11e63ff93000000000000000000000000b7c1fa3d7276061977680e150f89f747560a22a2000000000000000000000000f37d50121e9681e4c4303e9be26b83980b416590000000000000000000000000e09f34234e85505a0182f86e10d3c768c7abc0ff000000000000000000000000caaa26b476b6935b9b2bb37eed2b158601b80df8"},"latest"],"id":622,"jsonrpc":"2.0"}'

curl --location --request POST 'https://zksync2-testnet.zksync.dev/' \
--header 'Content-Type: application/json' \
--data-raw '{"method":"eth_call","params":[{"to":"0xfcfb989b985d4af15d2e4e70d2de1710326f0164","data":"0x67e256100000000000000000000000009a733826c3313f175032e3a7df0f2b487ebb5f5600000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000005000000000000000000000000260b6cf38e59fee9d0903389124b65a11e63ff93000000000000000000000000b7c1fa3d7276061977680e150f89f747560a22a2000000000000000000000000f37d50121e9681e4c4303e9be26b83980b416590000000000000000000000000e09f34234e85505a0182f86e10d3c768c7abc0ff000000000000000000000000caaa26b476b6935b9b2bb37eed2b158601b80df8"},"latest"],"id":515,"jsonrpc":"2.0"}'

> - …Minimal – Use as little code as possible that still produces the same problem
> - …Complete – Provide all parts someone else needs to reproduce your problem in the question itself
> - …Reproducible – Test the code you're about to provide to make sure it reproduces the problem

More details can be found at https://stackoverflow.com/help/minimal-reproducible-example

**Additional details**
- Contents of `package.json` file?
- Contents of `hardhat.config` file?
- What version of the compiler did you use?
- Have you tried this on other networks or testnets successfully?

**To Reproduce**

**Screenshots**
<img width="878" alt="image" src="https://user-images.githubusercontent.com/20899383/190069874-f1c37a37-8635-478b-beef-011f8fa5a2ee.png">
<img width="886" alt="image" src="https://user-images.githubusercontent.com/20899383/190069908-0da23118-a7fa-4ce4-97da-c60eb7a81bce.png">

**Comment by bxpana** [comment]
@xiangpengm this is something that the team is looking into and working on. We will let you know when this is resolved

**Comment by bxpana** [comment]
@xiangpengm We put out an update last week that should resolve this. Please let me know if this is resolved on your end
