### ISSUE TITLE
Not able to run the docs locally 

### ISSUE THREAD

**Issue by supernovahs** [matter-labs/zksync-v2-issues#11]
**Describe the issue**
I am running 

```
yarn docs:dev
```
It throws error command not found: vuepress

**Minimal Reproducible Example Code**
```
yarn docs:dev
```
I ran all the commands as given in Readme

**Screenshots**
.
<img width="779" alt="Screenshot 2022-10-06 at 6 53 29 PM" src="https://user-images.githubusercontent.com/91280922/194327511-5635dfae-6f30-4e9d-8906-4ddd3f05a024.png">

<img width="844" alt="Screenshot 2022-10-06 at 6 56 10 PM" src="https://user-images.githubusercontent.com/91280922/194327489-bc643ee9-b6c5-439d-aeec-24b146dab666.png">

**Comment by bxpana** [comment]
@supernovahs are you running this on MacOS or what OS?

**Comment by supernovahs** [comment]
Issue resolved
 Was working  on Mac os .
I was using yarn which was throwing errors .
Using NPM solved the problem
