### ISSUE TITLE
error: timeout

### ISSUE THREAD

**Issue by liny52** [matter-labs/zksync-v2-issues#12]
**Describe the issue**
I use the script to find all contract accounts on the testnet, and it will timeout soon

**js Code**
> const zksync = require("zksync-web3");
const ethers = require("ethers");
const provider = new zksync.Provider("https://zksync2-testnet.zksync.dev");
const erc721ABI = require("../abi/erc721ABI.json");
let nftContractAddress = [];
getTransactionsByAddr(0, 500);
async function getTransactionsByAddr(startBlockNumber, endBlockNumber) {
  console.log(
    "Searching for transactions within blocks " +
      startBlockNumber +
      " and " +
      endBlockNumber
  );
 for (var i = startBlockNumber; i <= endBlockNumber; i++) {
    if (i % 1000 == 0) {
      console.log("Searching block " + i);
    }
    var block = await provider.getBlock(i, true);
    if (block != null && block.transactions != null) {
      block.transactions.forEach(function (e) {
        // console.log(`blocknumber: ${e.blockNumber}`);
        getTransactionReceipt(e);
      });
    }
  }
  console.log("nftContractAddress: ", nftContractAddress);
}
async function getTransactionReceipt(txhash) {
  var receipt = provider.getTransactionReceipt(txhash).then((res) => {
    if (res.contractAddress != null) {
      console.log(`contractAddress: ${res.contractAddress}`);
      isERC721Contract(res.contractAddress);
    }
  });
}
function isERC721Contract(address) {
  // console.log("address: ", address);
  // console.log("bool: ", !contractAddress.includes(address));
  if (!nftContractAddress.includes(address)) {
    var contract = new ethers.Contract(address, erc721ABI, provider);
    //   console.log(contract);
    contract
      .supportsInterface("0x80ac58cd")
      .then((res) => {
        console.log("isERC721: ", res);
        if (res) {
          console.log(`nftAddress: ${address}`);
          nftContractAddress.push(address);
          console.log(nftContractAddress);
        }
      })
      .catch((err) => {
        // console.log(err);
      });
  }
}

**package.json**
>{
  "name": "nft-web3js",
  "version": "1.0.0",
  "main": "index.js",
  "devDependencies": {
    "@openzeppelin/contracts": "^4.7.3",
    "@types/node": "^18.7.23",
    "body-parser": "^1.20.0",
    "cors": "^2.8.5",
    "dotenv": "^16.0.2",
    "ethers": "^5.7.0",
    "express": "^4.18.1",
    "mysql": "^2.18.1",
    "web3": "^1.7.5",
    "zksync-web3": "^0.9.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}

**To Reproduce**
node xxxx.js

**Screenshots**

![image](https://user-images.githubusercontent.com/40197424/195045830-84c23de6-a569-46b8-bedd-f783b8963069.png)

**Comment by bxpana** [comment]
@liny52 what contract accounts are you looking for? The zkSync System contracts or what contracts?

**Comment by bxpana** [comment]
@liny52 was this something that was working before the regenesis yesterday? Did you already update your packages, delete your `artifacts-zk` and `cache-zk` folders?

**Comment by liny52** [comment]
> @liny52 was this something that was working before the regenesis yesterday? Did you already update your packages, delete your `artifacts-zk` and `cache-zk` folders?

I am looking for all nft contract accounts, Regenesis also didn't work before, and an error occurred after a while. I didn't involve the contract, just a simple script, there was no artifacts-zk and cache-zk folders, you can run this js and see if it will be the same as me error

**Comment by bxpana** [comment]
@liny52 ok makes sense. You'll at least want to update `zksync-web3` as 0.9.0 is outdated now

Does it always fail at the same spot or does it change each time?

**Comment by liny52** [comment]
> @liny52 ok makes sense. You'll at least want to update `zksync-web3` as 0.9.0 is outdated now
> 
> Does it always fail at the same spot or does it change each time?

I have updated zksync-web3 to 0.11.0, but the error still occurs, it does not appear in the same place after running 2 times
![image](https://user-images.githubusercontent.com/40197424/195478990-6abb2519-620a-4708-930b-001638703778.png)

![image](https://user-images.githubusercontent.com/40197424/195479047-226ded03-71a6-4200-98d6-6b6d44093e92.png)

**Comment by bxpana** [comment]
@liny52 
This is pretty heavy script as that runs through all the transactions of every block. We were able to run it for a while (5mins) with no issues with the latest versions of our libraries. 

In any case, I'd suggest saving the contract addresses to a file (using `fs.writeFileSync()`) and break down the execution of the whole script into smaller block batches, while also adding retries if the connection is lost at some point.
