### ISSUE TITLE
Is the zkSync v2.0 mainnet ready?

### ISSUE THREAD

**Issue by YuXiaoCoder** [matter-labs/zksync-v2-issues#13]
Is the zkSync v2.0 mainnet ready? I want to migrate from v1.0 to v2.0 and need to deploy RPC nodes

**Comment by bxpana** [comment]
@YuXiaoCoder Not yet, but you can see our roadmap here https://blog.matter-labs.io/100-days-to-mainnet-6f230893bd73

We currently have 17 days until Baby Alpha and projects are able to sign up for project registration. You can read more in our article about the project registration process https://blog.matter-labs.io/project-registration-is-now-open-for-zksync-2-0-mainnet-alpha-43616acd422d
