### ISSUE TITLE
zksync-beta scan opens unknown page for L1 Txs

### ISSUE THREAD

**Issue by cmnisal** [matter-labs/zksync-v2-issues#15]
**Describe the issue**
When Opening a hyperlink to L1 from the `https://goerli-beta-scan.zksync.dev/` it goes as `https://goerli-beta.etherscan.io/` site which is wrong. 

**Expected behavior**
it should open the exact same old goerli etherscan. but hyper link goes as same subdomain for the project.

**Minimal Reproducible Example Code**
> Withdraw from L2 to L1 on the goerli chain and open the zksync scan.
> click on the L1 link for just click on a l2 button

**Comment by bxpana** [comment]
@cmnisal do you have an example link? Just tested it out and everything is working as expected https://explorer.zksync.io/tx/0xc38ee0853e2b307b633f2824ec3912afb544929163644b908f847c85c16ffa09

**Comment by cmnisal** [comment]
Steps to Reproduce

Open this tx. - https://goerli-beta-scan.zksync.dev/explorer/transactions/0xcf42df141a1afd8678d3556c845f88064aa8b4a22a9fb06298365f9b465fd2d3
Click on the L1 tx hash or L1 to address.
It routes to goerli-beta.etherscan.io

There's no goerli-beta etherscan and it should route to goreli.etherscan.io

**Comment by bxpana** [comment]
@cmnisal Ah that makes sense, thank you I'll let the team know and get that taken care of
