### ISSUE TITLE
Can't deploy vyper contract

### ISSUE THREAD

**Issue by pandadefi** [matter-labs/zksync-v2-issues#16]
**Describe the issue**
Can't deploy yearn vault contract

**Expected behavior**
Should be able to deploy.

**Minimal Reproducible Example Code**

- clone https://github.com/pandadefi/yearn-vaults
- checkout on the zk_sync_deploy branch 
- yarn
- make sure docker is started
- yarn hardhat compile
- set your private key in the deploy [script](https://github.com/pandadefi/yearn-vaults/blob/zk_sync_deploy/deploy/deploy.ts#L10)
- yarn hardhat deploy-zksync 

**Additional details**
- Contents of `package.json` file?
https://github.com/pandadefi/yearn-vaults/blob/zk_sync_deploy/package.json

- Contents of `hardhat.config` file?
https://github.com/pandadefi/yearn-vaults/blob/zk_sync_deploy/hardhat.config.ts

- What version of the compiler did you use?
1.2.0
- Have you tried this on other networks or testnets successfully?
Yes

Failed TX: https://explorer.zksync.io/tx/0x0579502a2bd912bc76ccbf0916ded848e9793ed36cc1047de9589e387c8b5ab6

**Comment by bxpana** [comment]
@pandadefi a new upgrade for zkvyper is out and we have been able to deploy the provided contract. Can you please test on your end after upgrading your packages?

**Comment by bxpana** [comment]
@pandadefi no, you should probably delete your cache folders, run `yarn upgrade --latest`, and then recompile and deploy. Can you try again after do that?

**Comment by bxpana** [comment]
@bxpana hmmm, still getting the `cannot estimate gas; transaction may fail or may require manual gas limit` error?

**Comment by bxpana** [comment]
@pandadefi thank you very much. Looks like we were able to reproduce the error and we're looking into it. Thanks for your patience 😁

**Comment by bxpana** [comment]
@pandadefi nothing yet, but I'll check on this to see if I can get an update for you guys

**Comment by DarkGhost7** [comment]
Thanks vyper support is a blocker for yearn and curve to launch on testnet/mainnet for yall.

**Comment by bxpana** [comment]
@pandadefi no update on this specific issue yet. We've been able to replicate but not figure out exactly what's causing it quite yet. We'll keep you updated

**Comment by bxpana** [comment]
@pandadefi The compiler update is a small step toward resolving the deployment issues. We don't expect it to work for every contract, but if you are able to update and try again to see if it works it would really help out. 
latest version `1.2.1`
Update `hardhat-zksync-vyper`
update `hardhat.config.ts` compiler version to `1.2.1`
Delete the `artifacts-zk` and `cache-zk` 

Let us know if you still get the same result or if anything changes for you

**Comment by pandadefi** [comment]
With the changes made on this [branch](https://github.com/yearn/yearn-vaults/compare/master...pandadefi:yearn-vaults:zk_sync_deploy)
I am now getting the following error:

```
Error: Command failed: /Users/panda/Library/Caches/hardhat-nodejs/compilers-v2/zksolc/zksolc-v1.2.1 --standard-json --solc /Users/panda/Library/Caches/hardhat-nodejs/compilers-v2/macosx-amd64/solc-macosx-amd64-v0.8.16+commit.07a7930e
unknown variant `evm.bytecode`, expected one of `abi`, `evm.methodIdentifiers`, `storageLayout`, `ast`, `irOptimized`, `evm.legacyAssembly` at line 1 column 86051
```

This makes me think something is falling with the solidity compiler, the vyper compiler isn't running because of the solidity compiler error.

**Comment by bxpana** [comment]
@pandadefi did you update the hardhat plugin too? Seems like we saw this issue earlier, but updating the hardhat plugin resolved it.

**Comment by pandadefi** [comment]
Yes it's 0.3.12.

**Comment by bxpana** [comment]
@pandadefi from our team: 

> I've trying to replicate the issue. Cloned the repo and checked out in the branch "zk_sync_deploy'". I've had to install the openzeppelin dependency manually and change the vyper version in the Registry.vy contract from 0.2.11 to 0.3.3. I'm reviewing it with the team internally but I wanted to confirm with you if the error is compiling or deploying the contracts? If it's deploying, can you share the deployment script you're using?

**Comment by pandadefi** [comment]
> @pandadefi from our team:
> 
> > I've trying to replicate the issue. Cloned the repo and checked out in the branch "zk_sync_deploy'". I've had to install the openzeppelin dependency manually and change the vyper version in the Registry.vy contract from 0.2.11 to 0.3.3. I'm reviewing it with the team internally but I wanted to confirm with you if the error is compiling or deploying the contracts? If it's deploying, can you share the deployment script you're using?

I am getting an issue with the solidity compilation since updating to the latest version. Before it was a deployment issue (check this issue history)
The deploy script can be found here: https://github.com/pandadefi/yearn-vaults/blob/zk_sync_deploy/deploy/deploy.ts#L10

**Comment by bxpana** [comment]
@pandadefi thank you very much. I'll get that over to our team and have them look into things. Once again appreciate your patience!!

**Comment by bxpana** [comment]
@pandadefi from our team
> Just FYI, I've managed to compile the project with v1.2.1 but I'm using the macos-arm64 binary and the issue is reported with the macos-amd64 one, so we're trying to replicate it internally
we've been able to compile the project using the macos-amd64 compiler (and the linux one as well). Can you try using this fork that I've created? just clone, install deps with yarn and run yarn hardhat compile. https://github.com/uF4No/yearn-zk-test

**Comment by pandadefi** [comment]
deployed on: https://goerli.explorer.zksync.io/address/0xec0cEfa948F382cA9F4f430596bFEA853Ba53c3c#transactions

**Comment by bxpana** [comment]
@pandadefi great to hear! Appreciate the patience and let us know if you run into anything else.
