### ISSUE TITLE
NFT minting issue (chain id not available)

### ISSUE THREAD

**Issue by Endijuan33** [matter-labs/zksync-v2-issues#17]
![Screenshot_2022-10-27-23-38-00-122_com yandex browser](https://user-images.githubusercontent.com/28471097/198352593-27f38620-4c8b-4246-8e17-c540737ba32e.jpg)

when i want to do mint NFT the error appears on the metamask extension data.

reason: Transaction decoding is not available for chainId 280

please provide an explanation regarding this issue.

Version used:
Browser Name and version: Kiwi Browser v 105.0.5195.33 latest version (play store)
Operating System and version (desktop or mobile): Xiaomi redmi note 10 pro (android 12)

project:

[zkApe | 9999 unique and rare APEs.](https://zkape.io)

**Comment by bxpana** [comment]
@Endijuan33 thanks for submitting, but this is to report developer issues with code and not the frontend user experience. Thank you
