### ISSUE TITLE
Earlier shows error insufficient funds, Now unable to deploy the contract ( testnet )

### ISSUE THREAD

**Issue by mahendra-supraoracle** [matter-labs/zksync-v2-issues#19]
**Describe the issue**

I tried to deploy contract by following the guide ( https://v2-docs.zksync.io/api/js/getting-started.html ). 

Faced following issues while deploying contract today. 

1. Now, Contract deployment not proceeding.

2. Earlier getting the error ( **insufficient fund error.**  )
Even my wallet contain [0.7 ETH ](https://zksync2-testnet.zkscan.io/address/0xc5cF5080F59DE35Aff73ad2430c0f3EF6E73f985/transactions)

> `optimizer` setting is deprecated, optimizer is always enabled
> Running deploy script for the Greeter contract
> An unexpected error occurred:
> 
> Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":53,\"error\":{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value\"}}","error":{"code":-32000},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8d505808309779683097796830927c094c24215226336d22238a20a72f8e489c005b44c4a87038d7ea4c68000b8648340f549000000000000000000000000c5cf5080f59de35aff73ad2430c0f3ef6e73f985000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000038d7ea4c68000c080a04146a885c1410dcfe35449b532e0b549b647101a465cf84df9d66cf37114a5efa072634758a3884a13cf00558a4b6c85c1dca17066393f5af34005854fab269b77\"],\"id\":53,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://goerli.infura.io/v3/5918063957ef4e8bae0348d54fa14ebb"}, method="sendTransaction", transaction="0x02f8d505808309779683097796830927c094c24215226336d22238a20a72f8e489c005b44c4a87038d7ea4c68000b8648340f549000000000000000000000000c5cf5080f59de35aff73ad2430c0f3ef6e73f985000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000038d7ea4c68000c080a04146a885c1410dcfe35449b532e0b549b647101a465cf84df9d66cf37114a5efa072634758a3884a13cf00558a4b6c85c1dca17066393f5af34005854fab269b77", code=INSUFFICIENT_FUNDS, version=providers/5.7.2)
> 

**Expected behavior**
Contract able to deploy successfully

**Comment by mahendra-supraoracle** [comment]
Closing the issues, 

Needs to update the latest package.

**Comment by Hetape** [comment]
> Closing the issues,
> 
> Needs to update the latest package.

which package should I need to update?
I'm getting same error like shown above.
