### ISSUE TITLE
Multicall contract is not working properly

### ISSUE THREAD

**Issue by SpaceFinance** [matter-labs/zksync-v2-issues#3]
After the test network is upgraded, the Multicall contract does not work properly. Please check the cause.

code: https://github.com/Haehnchen/solidity-multicall-contract/blob/main/multicall.sol

address: 0x9B16c3D9FFDB1A33544d83d783e3a1F95312f544

**Comment by bxpana** [comment]
@SpaceFinance did you still need this open or did you get this resolved?
