### ISSUE TITLE
Getting the error `RangeError: Maximum call stack size exceeded` when calling the `Provider` class

### ISSUE THREAD

**Issue by adrianwsw** [matter-labs/zksync-v2-issues#5]
Been getting the RangeError:Maximum call stack size exceeded from time to time, which points to some kind of recursion in the constructor of  Provider class. May I know if this is a bug not being reported yet or I have done sth wrong in initiating the Provider class?
<img width="766" alt="Screenshot 2022-09-19 at 11 05 59 AM" src="https://user-images.githubusercontent.com/86141831/191489542-9fb26890-891f-49a7-baef-b97ca0f3e131.png">
Line 16-20 of build/provider.js:
` this.formatter.blockTag = (tag) => {
if (tag == 'committed' || tag == 'finalized') {
                return tag;
            }
            return blockTag(tag);
        };`

**Comment by bxpana** [comment]
@adrianwsw thanks for submitting. Can we get some more details for this issue? Can you share the minimal reproducible code, the contents of your `package.json`, and steps to reproduce? Then we can investigate and see what might be causing this issue.
