### ISSUE TITLE
Error: timeout (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":59,\"jsonrpc\":\"2.0\"}"

### ISSUE THREAD

**Issue by ouyangguang5089** [matter-labs/zksync-v2-issues#7]
Error: timeout (requestBody="{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":59,\"jsonrpc\":\"2.0\"}", requestMethod="POST", timeout=120000, url="https://zksync2-testnet.zksync.dev", code=TIMEOUT, version=web/5.7.1)
    at Logger.makeError (/mnt/c/ouyang/soft/work-soft/blockchain/hardhat/workspaces/greeter-example/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Timeout._onTimeout (/mnt/c/ouyang/soft/work-soft/blockchain/hardhat/workspaces/greeter-example/node_modules/@ethersproject/web/src.ts/index.ts:228:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  reason: 'timeout',
  code: 'TIMEOUT',
  requestBody: '{"method":"eth_blockNumber","params":[],"id":59,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  timeout: 120000,
  url: 'https://zksync2-testnet.zksync.dev'
}
error Command failed with exit code 1.

This is my mistake, the version of zksync-web3 has been changed to 0.9.0, the version of zksolc has also been changed to 1.1.6, the artifacts-zk and cache-zk have also been deleted, but this error is still there, and I have not Did you do it?

**Comment by ouyangguang5089** [comment]
I used wsl2

**Comment by ouyangguang5089** [comment]
![image](https://user-images.githubusercontent.com/33918509/193178100-69512a62-7fb8-4838-b027-cfa19084faee.png)
![image](https://user-images.githubusercontent.com/33918509/193178130-04427576-7a52-4bdc-82e8-778f931f891c.png)

**Comment by bxpana** [comment]
@ouyangguang5089 thanks for reporting! When are you getting this error? Do you have the steps to reproduce the issue?

**Comment by liny52** [comment]
I have a similar problem, zkysnc-web3 is also 0.9.0

Error: missing response (requestBody="{\"method\":\"eth_getTransactionReceipt\",\"params\":[\"0xfd1c465ba9874165b501f77238c6cc11cff4fde993577d3cf2dd761dca0f778b\"],\"id\":1057,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"errno":-3008,"code":"ENOTFOUND","syscall":"getaddrinfo","hostname":"zksync2-testnet.zksync.dev"}, url="https://zksync2-testnet.zksync.dev", code=SERVER_ERROR, version=web/5.7.0)
    at Logger.makeError (/Users/yong/Downloads/nft-web3js/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/Users/yong/Downloads/nft-web3js/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /Users/yong/Downloads/nft-web3js/node_modules/@ethersproject/web/lib/index.js:255:36
    at step (/Users/yong/Downloads/nft-web3js/node_modules/@ethersproject/web/lib/index.js:33:23)
    at Object.throw (/Users/yong/Downloads/nft-web3js/node_modules/@ethersproject/web/lib/index.js:14:53)
    at rejected (/Users/yong/Downloads/nft-web3js/node_modules/@ethersproject/web/lib/index.js:6:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'missing response',
  code: 'SERVER_ERROR',
  requestBody: '{"method":"eth_getTransactionReceipt","params":["0xfd1c465ba9874165b501f77238c6cc11cff4fde993577d3cf2dd761dca0f778b"],"id":1057,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  serverError: Error: getaddrinfo ENOTFOUND zksync2-testnet.zksync.dev
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:111:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'zksync2-testnet.zksync.dev'
  },
  url: 'https://zksync2-testnet.zksync.dev'
}

package.json
`{
  "name": "nft-web3js",
  "version": "1.0.0",
  "main": "index.js",
  "devDependencies": {
    "@openzeppelin/contracts": "^4.7.3",
    "@types/node": "^18.7.23",
    "body-parser": "^1.20.0",
    "cors": "^2.8.5",
    "dotenv": "^16.0.2",
    "ethers": "^5.7.0",
    "express": "^4.18.1",
    "mysql": "^2.18.1",
    "web3": "^1.7.5",
    "zksync-web3": "^0.9.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}`

**Comment by ouyangguang5089** [comment]
> @ouyangguang5089感谢您的报告！你什么时候收到这个错误？你有重现问题的步骤吗？

Error received on September 30th，I tested according to this document, https://v2-docs.zksync.io/dev/developer-guides/hello-world.html#prerequisites, and changed the version of zksolc to 1.1.6, the compilation was successful, Error running deploy contract command (yarn hardhat deploy-zksync)

**Comment by bxpana** [comment]
@liny52 are you also getting this error when trying to deploy?

**Comment by bxpana** [comment]
@ouyangguang5089 we have just completed a regenesis. Can you delete the `cache-zk`, `artifacts-zk`, and `node_modules` folders, reinstall the modules and try to recompile and deploy?

Same to @liny52 if you are having an issue at the same spot.

I just tested out the example here https://v2-docs.zksync.io/dev/developer-guides/hello-world.html today without any issues
