### ISSUE TITLE
How to run the circuit files

### ISSUE THREAD

**Issue by supernovahs** [matter-labs/zksync-v2-issues#9]
**Describe the issue**
  I am trying to run the [file](https://github.com/matter-labs/zksync/blob/master/core/lib/utils/src/convert.rs) using
  cargo run  core/lib/utils/src/convert.rs

** Error**
`cargo run` could not determine which binary to run. Use the `--bin` option to specify a binary, or the `default-run` manifest key.
available binaries: add_seq_no, block_revert, block_sizes_test, dev-liquidity-token-watcher, dev-ticker-server, dummy_prover, exodus_test, flamegraph_target, gas_price_test, key_generator, loadnext, migration_test, multiplexed_gateway_watcher, parse_pub_data, plonk_step_by_step_prover, remove_proofs, revert_blocks_test, testkit_tests, tree_cache_updater, zksync_data_restore, zksync_event_listener, zksync_server

**Comment by bxpana** [comment]
@supernovahs this is for zkSync 1.0. Right now we are fully focused on getting zkSync 2.0 ready for mainnet so it will take a little longer to get support for zkSync 1.0. I'm going to close this ticket, but you can open it up in the issues section of the repo that you are working with.

**Comment by supernovahs** [comment]
> @supernovahs this is for zkSync 1.0. Right now we are fully focused on getting zkSync 2.0 ready for mainnet so it will take a little longer to get support for zkSync 1.0. I'm going to close this ticket, but you can open it up in the issues section of the repo that you are working with.

I was just trying to know how to run a circuit file  in your repo to understand the code , so I can find bugs in 2.0 on launch
